# -*- coding: utf-8 -*-
"""Plant Disease Image Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S6FRPIcLOG3X2cNwINQcMclXzzMpMJ6H

# ***Seeding for reproductibility***
"""

#set seeds for reproductibility
import random
random.seed(0)

import numpy as np
np.random.seed(0)

import tensorflow as tf
tf.random.set_seed(0)

"""# ***Importing the dependencies***"""

import os
import json
from zipfile import ZipFile
from PIL import Image

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models

"""# ***Data Curation***

Upload the kaggle.json file
"""

!pip install kaggle

kaggle_credentials = json.load(open('/content/kaggle.json'))

#setup kaggle API key as environment variables
os.environ['KAGGLE_USERNAME'] = kaggle_credentials['username']
os.environ['KAGGLE_KEY'] = kaggle_credentials['key']

!kaggle datasets download -d abdallahalidev/plantvillage-dataset

import shutil
shutil.rmtree('/content/PlantVillage')
shutil.rmtree('/content/plantvillage')

!ls

#Unzip the downloaded dataset
with ZipFile('/content/plantvillage-dataset.zip', 'r') as zip_ref:
  zip_ref.extractall()

print(os.listdir('/content/plantvillage dataset'))

print(len(os.listdir('/content/plantvillage dataset/segmented')))
print(os.listdir('/content/plantvillage dataset/segmented')[:5])

print(len(os.listdir('/content/plantvillage dataset/color')))
print(os.listdir('/content/plantvillage dataset/color')[:5])

print(len(os.listdir('/content/plantvillage dataset/grayscale')))
print(os.listdir('/content/plantvillage dataset/grayscale')[:5])

"""**Number of classes = 38**"""

print(len(os.listdir('/content/plantvillage dataset/color/Grape___healthy')))
print(os.listdir('/content/plantvillage dataset/color/Grape___healthy')[:5])

"""# ***Data Preprocessing***"""

#dataset path
base_dir='/content/plantvillage dataset/color'

image_path = '/content/plantvillage dataset/color/Apple___Cedar_apple_rust/025b2b9a-0ec4-4132-96ac-7f2832d0db4a___FREC_C.Rust 3655.JPG'

#read the image
img=mpimg.imread(image_path)
print(img.shape)
#display the image
plt.imshow(img)
plt.axis('off') #turn off the axis numbers
plt.show()

image_path = '/content/plantvillage dataset/color/Apple___Cedar_apple_rust/025b2b9a-0ec4-4132-96ac-7f2832d0db4a___FREC_C.Rust 3655.JPG'

#read the image
img=mpimg.imread(image_path)
print(img)

#image parameters
img_size = 224
batch_size = 32

"""# ***Train Test Split***"""

#Image Data Generator
data_gen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2  #Use 20% of data for validation
)

#Train Generator
train_generator = data_gen.flow_from_directory(
    base_dir,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    subset='training',
    class_mode='categorical'
)

#Validation Generator
validation_generator = data_gen.flow_from_directory(
    base_dir,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    subset='validation',
    class_mode='categorical'
)

"""# ***Convolutional Neural Network***"""

#Model Definition
model = models.Sequential()

model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(img_size, img_size, 3)))
model.add(layers.MaxPooling2D((2, 2)))

model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

model.add(layers.Flatten())
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(train_generator.num_classes, activation='softmax'))

model.summary()

#Compile the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

"""# ***Model Training***"""

#Training the model
history = model.fit(
    train_generator,
    steps_per_epoch = train_generator.samples // batch_size, # number of steps per epoch
    epochs = 5, #number of epoch
    validation_data = validation_generator,
    validation_steps = validation_generator.samples // batch_size #validati0on steps
)

"""# ***Model Evaluation***"""

#model evaluation
print('Evaluating model....')
val_loss, val_accuracy = model.evaluate(validation_generator, steps = validation_generator.samples // batch_size)
print(f'Validation Loss: {val_loss * 100:.2f}')
print(f'Validation Accuracy: {val_accuracy *100:.2f}')

#plot training and validation accuracy values
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

#plot training and validation loss values
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

"""# ***Building a predictive system***"""

#function to load and preprocess the image using pillow
def load_and_preprocess_image(image_path, target_size = (224,224)):
  #load the image
  img = Image.open(image_path)
  #resize the image
  img = img.resize(target_size)
  #convert the image to a numpy array
  img_array = np.array(img)
  #add batch dimension
  img_array = np.expand_dims(img_array, axis=0)
  #scale the image values to [0,1]
  img_array = img_array.astype('float32') / 255,
  return img_array

#function to predict the class of an image
def predict_image_class(model, image_path, class_indices):
  preprocessed_img = load_and_preprocess_image(image_path)
  predictions = model.predict(preprocessed_img)
  predicted_class_index = np.argmax(predictions, axis=1)[0]
  predicted_class_name = class_indices[predicted_class_index]
  return predicted_class_name

#create a mapping from class indices to class names
class_indices = {v: k for k, v in train_generator.class_indices.items()}

class_indices

#saving the class names as json files
json.dump(class_indices, open('class_indices.json', 'w'))

#example usage
#image_path='/content/test apple_black_rot .JPG'
image_path='/test corn(maize)_northern_leaf_blight.jpg'
#image_path='/strawberry_leaf_scrouch.JPG'
predicted_class_name = predict_image_class(model, image_path, class_indices)
#output the result
print(f'The predicted class  name is: {predicted_class_name}')

"""# ***Save the  model to Google Drive or local***"""

from google.colab import drive
drive.mount('/content/drive')

model.save('/content/drive/MyDrive/Colab Notebooks/Plant Disease Image Classifier.keras')